### ISSUE TITLE
Other fields to hide

### ISSUE THREAD

**Issue by philippeplatiau** [tomolimo/hidefields#1]
It's not an issue, but in case you need to hide these fields 

"Hardware Type"
"Location"
"Watchers" 

You can add these lines in the js file : 

  $("[name=my_items]").parents('tr').css('display', 'none');
  $("[title=Watcher]").parents('tr').css('display', 'none');
  $("[name=locations_id]").parents('tr').css('display', 'none');

Or course, regarding the "Watcher", it only works if your language is English

**Comment by tomolimo** [comment]
You should NOT use 

> $("[title=Watcher]").parents('tr').css('display', 'none');

But this: `$("[name='_users_id_observer[]']").parents('tr').css('display', 'none');`

if you want to hide the watchers row.

regards,
Tomolimo

**Comment by philippeplatiau** [comment]
Hi Tomolimo, 

Thanks for the tip. Indeed, I tested with $("[name=_users_id_observer[]]").parents('tr').css('display', 'none'); 

but that didn't work. I forgot the simple quotes around the _users_id_observer name... Shame on me. 

Nice work ! 

That should be nice to be able to hide some other fields on other views (not only in the "helpdesk/simplified interface")

Have a nice day ! 

Regards,

Philippe
