### ISSUE TITLE
PHP error: undefined index

### ISSUE THREAD

**Issue by Stoatwblr** [tomolimo/hidefields#3]
Undefined indexes may seem a minor complaint, but it leads to log spammng :(

  *** PHP Notice(8): Undefined index: glpiactiveprofile
  Backtrace :
  plugins/hidefields/setup.php:16                    
  inc/plugin.class.php:146                           plugin_init_hidefields()
  inc/includes.php:116                               Plugin::load()
  front/cron.php:43                                  include()
  ...hare/php/Zend/Loader/StandardAutoloader.php:290 include()
  ...hare/php/Zend/Loader/StandardAutoloader.php:231 Zend\Loader\StandardAutoloader->loadClass()
  :                                                  Zend\Loader\StandardAutoloader->autoload()
  :                                                  spl_autoload_call()
  plugins/tag/inc/tag.class.php:579                  class_exists()
  plugins/tag/setup.php:96                           PluginTagTag::getCurrentItemtype()
  inc/plugin.class.php:146                           plugin_init_tag()
  inc/includes.php:116                               Plugin::load()
  front/cron.php:43                                  include()

**Comment by tomolimo** [comment]
Hello,
Could you give more details?
GLPI version, PHP version?
Thank you,
Regards,
Tomolimo

**Comment by Stoatwblr** [comment]
Glpi versions 9 (various)

 php --version
PHP 5.6.32 (cli) (built: Oct 25 2017 07:00:59) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

**Comment by Stoatwblr** [comment]
https://stackoverflow.com/questions/4261133/php-notice-undefined-variable-notice-undefined-index-and-notice-undef

**Comment by Stoatwblr** [comment]
Hi Tomolino, it's still ocurring.

Glpi 9.2.2
PHP 7.2.5RC1 (cli) (built: Apr 11 2018 10:37:55) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies

**Comment by tomolimo** [comment]
Hello @Stoatwblr 
For the next months, as I don't have time to provide a fix, please feel free to propose a Pull Request to this issue.
Thank you,
Regards,
Tomolimo

**Comment by tomolimo** [comment]
As no pull request has been proposed, I close this issue
Feel free to re-open
